name: build

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        # ubuntu-18.04
        - os: ubuntu-18.04
          cc: ""
          php: 7.1
        # ubuntu-18.04 with php7.4
        - os: ubuntu-18.04
          cc: ""
          php: 7.4
        # ubuntu-20.04
        - os: ubuntu-20.04
          cc: ""
          php: 7.4
        # ubuntu-20.04 with gcc-10
        - os: ubuntu-20.04
          cc: CC=/usr/bin/gcc-10
          php: 7.4
          setup: sudo apt-get install -y gcc-10
        # macos-10.15
        - os: macos-10.15
          cc: ""
          php: 7.4
    steps:
    - uses: actions/checkout@v2
    - name: Setup older PHP supported by swig
      uses: shivammathur/setup-php@v2
      if: runner.os == 'macOs'
      with:
        php-version: ${{ matrix.php }}
        tools: php-config
    - name: setup
      if: ${{ matrix.setup }}
      run: ${{ matrix.setup }}
    - name: install dependencies on Linux
      if: runner.os == 'Linux'
      run: sudo apt-get install -y libfuse-dev swig3.0 uthash-dev tcl-dev python-dev libftdi1-dev libavahi-client-dev check
    - name: install dependendencies on macOS
      if: runner.os == 'macOs'
      run: brew install autoconf automake libtool pkg-config swig php libftdi check
    - name: bootstrap
      run: ./bootstrap
    - name: configure
      run: ${{ matrix.cc }} ./configure --with-php=php${{ matrix.php }} --with-phpconfig=php-config${{ matrix.php }}
    - name: make
      run: make
    - name: check
      run: make check

  dist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: bootstrap
      run: ./bootstrap
    - name: configure
      run: ./configure
    - name: make dist (.tar.gz)
      run: make dist-gzip
    - uses: actions/upload-artifact@v2
      with:
        name: source-dist
        path: owfs-*.*p*.tar.gz

  build-from-dist:
    needs: dist
    runs-on: ubuntu-latest
    steps:
    # FIXME: reusing steps from "jobs.build".
    # Verify if this is possible without copying verbatim.
    # Natural solution would be YAML anchors and pointers, but these
    # are not supported yet.
    - name: install dependencies on Linux
      if: runner.os == 'Linux'
      run: sudo apt-get install -y libfuse-dev swig3.0 uthash-dev tcl-dev python-dev libftdi1-dev libavahi-client-dev check
    - uses: actions/download-artifact@v2
      with:
        name: source-dist
    - name: extract sources
      run: tar -x -f owfs-*.tar.gz --strip-components 1
    - name: configure
      run: ./configure --with-php=php7.4 --with-phpconfig=php-config7.4
    - name: make
      run: make
